sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t taxd/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true taxd/docker-react-app npm run test -- --coverage 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-300490924037"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY